import type { Metadata } from 'next';
import { Nav } from './components/ui/Nav';
import './globals.css';
import { blackHanSans, inter } from './fonts';
import { Footer } from './components/ui/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${blackHanSans.variable}`}>
        <div className='flex flex-col justify-center items-center min-h-screen text-stone-800 dark:text-main-dark dark:bg-main-dark'>
          <Nav />
          <main className='flex-grow flex flex-col items-center w-full px-12 md:flex-row md:items-baseline'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
